var aplayer_css = root_domain + "/aplayer/dist/APlayer.min.css"
var aplayer_js = root_domain + "/aplayer/dist/APlayer.min.js"
var meeting_js = root_domain + "/js/Meting.min.js"
var loadaplayer = "<link rel=\"stylesheet\" href=\"" + aplayer_css + "\"><script src=\""+ aplayer_js +"\"></script><script src=\""+ meeting_js +"\"></script>"
var aplayerconf = "<!-- 我使用的APlayer本体 -->"
aplayer += "<div class=\"aplayer\" "
aplayer += "data-id=\"450007071\" "
aplayer += "data-server=\"netease\" "
aplayer += "data-type=\"playlist\" "
aplayer += "data-fixed=\"true\" "
aplayer += "data-autoplay=\"false\" "
aplayer += "data-order=\"random\" "
aplayer += "data-volume=\"0.55\" "
aplayer += "data-preload=\"true\""
aplayer += "data-showlrc=\"0\" >"
"</div>"
"<!--如果将本体放在body里面导致页面加载出现问题，请尝试放到body体后面-->"

var aplayer = loadaplayer + aplayerconf